enum PlateColorEnum {
  RED
  BLUE
  GREEN
  YELLOW
}

enum PlateFormatEnum {
  SQUARE
  CIRCLE
  SOUP
  PASTA
}

enum OrderStateEnum {
  WAITING
  PAID
  CANCELED
}

type Plate {
  id: String!
  name: String!
  color: PlateColorEnum!
  format: PlateFormatEnum!
  radius: Int!
  price: Int!
}

type Order {
  id: String!
  client_id: String!
  state: OrderStateEnum!
}

type Client {
  id: String!
  email: String!
  first_name: String!
  last_name: String!
  address: String!
}

input CreatePlateInput {
  name: String!
  color: PlateColorEnum!
  format: PlateFormatEnum!
  radius: Int!
  price: Int!
}

type Query {
  Plates: [Plate!]!
  Plate(id: String!): Plate
}

type Mutation {
  createPlate(data: CreatePlateInput!): Boolean!
}
